config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  get '/signup', to: 'users#new'
  get '/login', to: 'user_sessions#new'
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'

  resources :users, only: %i[create]
  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :body, presence: true

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :email, uniqueness: true, presence: true
  validates :username, uniqueness: true, presence: true
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  has_many :posts, dependent: :destroy

  def own?(object)
    id == object.user.id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  add_flash_types :success, :info, :warning, :danger

  protected

  def not_authenticated
    redirect_to login_url, danger: "please login"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  skip_before_action :require_login, only: %i[index]
  PER_PAGE = 15

  def index
    @posts = Post.order(created_at: :desc).page(params[:page]).per(PER_PAGE)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.save
      redirect_to root_path, success: "created a post"
    else
      render :new
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path, success: "updated a post"
    else
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to root_path, success: "deleted a post"
  end

  private

  def post_params
    params.require(:post).permit(:body, :image)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  skip_before_action :require_login, only: %i[new create]

  def new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path, success: "successfully login"
    else
      flash.now[:danger] = "please retry"
      render :new
    end
  end

  def destroy
    logout
    redirect_to login_path, success: "bey bey"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, success: "create a user"
    else
      flash.now[:danger] = "please retry..."
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Retry
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  body
    = render 'shared/header_erb'
    = render 'shared/flash_messages'
    .container
      = yield

app/views/posts/_post.html.slim
.card.mb-5.post
  .card-header
    .d-flex.align-items-center
      = image_tag 'profile-placeholder.png', size: '40x40', class: 'rounded-circle mr-1'
      = post.user.username
      - if current_user&.own?(post)
        .ml-auto
          = button_to post_path(post), class: 'mr-3', method: :delete, data: { confirm: "本当に削除しますか?" } do
            = icon 'far', 'trash-alt', class: 'fa-lg'
          = link_to edit_post_path(post) do
            = icon 'far', 'edit', class: 'fa-lg'
  .card-img-top
    - if post.image.attached?
      = image_tag post.image, size: "854x500"
  .card-body
    .card-text
      = post.body

app/views/posts/edit.html.slim
= form_with model: @post, local: true do |f|
  .form-group
    = f.label :body
    = f.text_area :body, class: "form-control"
  .form-group
    = f.label :image
    = f.file_field :image, class: "form-control"
    - if @post.image.attached?
      = image_tag @post.image, size: "100x100"
  = f.submit

app/views/posts/index.html.slim
.row
  .col-md-8.col-12
    - if @posts.present?
      = render @posts
    - else
      | not post
    = paginate @posts
  .col-md-4.col-12
    .profile-box.mb-3
      = image_tag 'profile-placeholder.png', size: '50x50', class: 'rounded-circle mr-1'
      = current_user.username
    .users-box
      .card
        .card-header
          | ユーザー
        .card-body
          .user.mb-3
            = image_tag 'profile-placeholder.png', size: '40x40', class: 'rounded-circle mr-1'
            | はりゅ
          .user.mb-3
            = image_tag 'profile-placeholder.png', size: '40x40', class: 'rounded-circle mr-1'
            | 上田
          .user.mb-3
            = image_tag 'profile-placeholder.png', size: '40x40', class: 'rounded-circle mr-1'
            | 広大
          .user.mb-3
            = image_tag 'profile-placeholder.png', size: '40x40', class: 'rounded-circle mr-1'
            | ken
        .card-footer
          = link_to 'すべて見る', '#'

app/views/posts/new.html.slim
= form_with model: @post, local: true do |f|
  = render 'shared/error_messages', object: @post
  .form-group
    = f.label :body
    = f.text_area :body, class: "form-control"
  .form-group
    = f.label :image
    = f.file_field :image, class: "form-control"
  = f.submit

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_messages.alert-danger
    ul.mb-0
      - object.errors.full_messages.each do |msg|
        li= msg

app/views/shared/_flash_messages.html.slim
- flash.each do |message_type, message|
  div class=("alert alert-#{message_type}") = message

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to 'RETRY', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarTogglerDemo02.collapse.navbar-collapse
    form.form-inline.my-2.my-lg-0.mr-auto
      input.form-control.mr-sm-2 placeholder="Search" type="search" /
      button.btn.btn-outline-success.my-2.my-sm-0 type="submit"  Search
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
        a.nav-link href="#"
        = link_to new_post_path, class: 'nav-link' do
          = icon 'far', 'image', class: 'fa-lg'
      li.nav-item
        a.nav-link href="#"
          = icon 'far', 'heart', class: 'fa-lg'
      li.nav-item
        a.nav-link href="#"
          = icon 'far', 'user', class: 'fa-lg'
      li.nav-item
        = button_to 'ログアウト', logout_path, class: 'nav-link', method: :delete

app/views/shared/_header_erb.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">RETRY</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "POSTS", posts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "CREATE", new_post_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "#", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "#", "#", class: "nav-link" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <%= button_to "SIGN OUT", logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "SIGN IN", login_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/user_sessions/new.html.slim
.card.my-5
  .card-header.text-center
    | SIGN IN
  = form_with url: login_path, class: 'card-body', local: true do |f|
    .form-group
      = f.label :email, class: 'bmb-label-floating'
      = f.email_field :email, class: 'form-control'
    .form-group.mb-2
      = f.label :password, class: 'bmb-label-floating'
      = f.password_field :password, class: 'form-control'
    = f.submit 'ログイン', class: 'btn btn-raised btn-primary'
.card
  .card-body
    | アカウントをお持ちでないですか？
    = link_to "登録", signup_path

app/views/users/new.html.slim
.card.my-5
  .card-header.text-center
    | SIGN UP
  = form_with model: @user, class: 'card-body', local: true do |f|
    = render 'shared/error_messages', object: @user
    .form-group
      = f.label :email, class: 'bmb-label-floating'
      = f.email_field :email, class: 'form-control'
    .form-group
      = f.label :username, class: 'bmb-label-floating'
      = f.text_field :username, class: 'form-control'
    .form-group.mb-2
      = f.label :password, class: 'bmb-label-floating'
      = f.password_field :password, class: 'form-control'
    .form-group.mb-2
      = f.label :password_confirmation, class: 'bmb-label-floating'
      = f.password_field :password_confirmation, class: 'form-control'
    = f.submit 'ログイン', class: 'btn btn-raised btn-primary'
.card
  .card-body
    | アカウントをお持ちですか？
    = link_to "ログイン", login_path